name: build and push image to docker hub

on:
  push:
    branches: 
      - master
      - APIDevelopment
  pull_request:
    branches: 
      - master
      - APIDevelopment

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # Specify your Docker Hub username and repository name
  IMAGE_NAME: ranailayda/aura

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: |
        cd Back_End1_Aura
        docker-compose build --no-cache --force-rm 

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Specify the version of .NET Core you are using

      - name: Restore dependencies
        run: dotnet restore Back_End1_Aura.sln  # Adjust if your solution file has a different name
        
      - name: Build the solution
        run: dotnet build Back_End1_Aura.sln --no-restore --configuration Release
        
      - name: Run unit tests
        run: dotnet test Back_End1_Aura.sln --no-build --configuration Release --collect:"XPlat Code Coverage"

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Back_End1_Aura  # Adjusted context to include the directory
          dockerfile: Dockerfile  # Assuming Dockerfile is in the root of Back_End1_Aura directory
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
